# Generated by Django 3.1.1 on 2020-09-23 07:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('Current_age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('fem', 'Female'), ('ma', 'Male')], max_length=50)),
                ('State', django_countries.fields.CountryField(max_length=2)),
                ('City_street', models.CharField(max_length=50)),
                ('Postal_code', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Telephone_number', models.IntegerField()),
                ('Mother_tongue', models.CharField(max_length=50)),
                ('Payment_method', models.CharField(max_length=50)),
            ],
        ),
    ]
