# Generated by Django 3.1.1 on 2020-09-23 08:16

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('std_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='City_street',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
