# Generated by Django 3.1.1 on 2020-09-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('std_profile', '0002_auto_20200923_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std_profile.profile')),
            ],
        ),
    ]
